### ISSUE TITLE
Geometric Toolbox Not Available

### ISSUE THREAD

**Issue by abdul-mannan-khan** [vkotaru/quad_geometric_control#1]
Dear Venkata Naga Prasanth Kotaru,

First of all, I thank you for your greatness to make this code available for users like me to learn and explore. 

Secondly, I shall highly appreciate if you could please spare some time to help me regarding your research on geometric control. The problem is that I cannot find 'Geometric Control Toolbox'. I believe it is the main reason that simulation is not working. 
 
Your few moments will contribute hours in my research and it will mean a lot for me.
 
Much appreciated.

**Comment by vkotaru** [comment]
Hi,

Download and extract https://github.com/sir-avinash/Geometry-Toolbox

In line 22, of main_quad.m change path location to the above extracted folder.
