### ISSUE TITLE
Undefined function 'animate_3dquad'

### ISSUE THREAD

**Issue by abdul-mannan-khan** [vkotaru/quad_geometric_control#2]
Dear Venkata Naga Prasanth Kotaru,

Thank you so much for providing the link for the toolbox. It worked. It is highly appreciated. 

I want to bring into your notice that function for animation is not available which is `animate_3dquad().`
It will be really nice to see the animation. 

Thank You so much for your precious time. 

Best Wishes, 
Dr. A. Mannan

**Comment by vkotaru** [comment]
Hi,
I currently do not have the code for it. I will update the repository once I complete writing it.

**Comment by abdul-mannan-khan** [comment]
Hi Vkotaru,

Thanks. I wait. :)

**Comment by abdul-mannan-khan** [comment]
Hi Vkotaru,

It has been really long time to write you. I just want to know could you please find the function `animate_3dquad()`?

Appreciate your efforts. Thank you.

**Comment by MAminSFV** [comment]
Any updates?

**Comment by vkotaru** [comment]
Check the latest commit.

**Comment by MAminSFV** [comment]
Thank you for your quick response!
