### ISSUE TITLE
Reference paper or document

### ISSUE THREAD

**Issue by PulkitRustagi** [vkotaru/quad_geometric_control#4]
Hi, 

Can you site the paper/document you are using for the math of generating desired Omega (Ω_d) and desired states (x_d) for the error computation?
 ![image](https://user-images.githubusercontent.com/19322202/98863600-39197f80-242e-11eb-9ec4-af45bef3947e.png)

 Thanks.

**Comment by vkotaru** [comment]
https://ieeexplore.ieee.org/document/5980409
